import { ethereum } from "thirdweb/chains";
import { ConnectButton, darkTheme } from "thirdweb/react";
import { createThirdwebClient } from "thirdweb";
import { inAppWallet, createWallet } from "thirdweb/wallets";

const client = createThirdwebClient({
  clientId: "....",
});

const wallets = [
  inAppWallet({
    auth: {
      options: [
        "google",
        "discord",
        "telegram",
        "email",
        "x",
        "passkey",
        "phone",
        "apple",
        "guest",
        "coinbase",
        "github",
        "facebook",
        "epic",
        "tiktok",
      ],
    },
  }),
  createWallet("io.metamask"),
  createWallet("com.coinbase.wallet"),
  createWallet("io.rabby"),
  createWallet("io.zerion.wallet"),
  createWallet("com.trustwallet.app"),
  createWallet("org.uniswap"),
  createWallet("com.bitcoin"),
  createWallet("com.blockchain.login"),
  createWallet("io.trezor"),
  createWallet("com.hashpack.wallet"),
  createWallet("app.backpack"),
  createWallet("app.nightly"),
  createWallet("dev.auroracloud"),
  createWallet("com.withpaper"),
  createWallet("app.walletnow"),
  createWallet("one.mixin.messenger"),
  createWallet("io.legacynetwork"),
  createWallet("com.webauth"),
  createWallet("com.thirdweb"),
  createWallet("app.edge"),
  createWallet("com.bitpay"),
  createWallet("com.greengloryglobal"),
  createWallet("me.rainbow"),
  createWallet("io.1inch.wallet"),
  createWallet("com.ledger"),
  createWallet("com.binance.wallet"),
  createWallet("com.fireblocks"),
  createWallet("com.safepal"),
  createWallet("com.elrond.maiar.wallet"),
  createWallet("com.bybit"),
  createWallet("im.token"),
  createWallet("com.okex.wallet"),
  createWallet("co.arculus"),
  createWallet("com.wemixplay"),
  createWallet("com.wigwam.wallet"),
  createWallet("app.subwallet"),
  createWallet("so.onekey.app.wallet"),
  createWallet("me.haha"),
  createWallet("com.kraken"),
  createWallet("xyz.argent"),
  createWallet("app.kabila"),
  createWallet("app.core.extension"),
  createWallet("com.chain"),
  createWallet("com.gemwallet"),
  createWallet("io.leapwallet"),
  createWallet("com.oasys-wallet"),
  createWallet("com.coldwallet"),
  createWallet("com.bitso"),
  createWallet("io.enjin"),
  createWallet("app.whitewallet"),
  createWallet("com.fastex.wallet"),
  createWallet("app.everspace"),
  createWallet("app.zeal"),
  createWallet("com.coolbitx.cwsapp"),
  createWallet("xyz.frontier.wallet"),
  createWallet("com.mtpelerin"),
  createWallet("app.keyring"),
  createWallet("com.coin98"),
  createWallet("com.coinomi"),
  createWallet("io.ethermail"),
  createWallet("org.bytebank"),
  createWallet("app.hbwallet"),
  createWallet("com.holdstation"),
  createWallet("io.universaleverything"),
  createWallet("com.foxwallet"),
  createWallet("org.bitizen"),
  createWallet("xyz.timelesswallet"),
  createWallet("io.zelcore"),
  createWallet("app.nicegram"),
  createWallet("com.xovawallet"),
  createWallet("com.unstoppabledomains"),
  createWallet("is.callback"),
  createWallet("org.thetatoken"),
  createWallet("net.gateweb3"),
  createWallet("us.binance"),
  createWallet("io.hyperpay"),
  createWallet("io.wallet3"),
  createWallet("com.coininn"),
  createWallet("org.dota168"),
  createWallet("com.bitpie"),
  createWallet("me.easy"),
  createWallet("com.neonwallet"),
  createWallet("com.unitywallet"),
  createWallet("com.beexo"),
  createWallet("social.halo"),
  createWallet("io.miraiapp"),
  createWallet("id.competence"),
  createWallet("com.midoin"),
  createWallet("baby.smart"),
  createWallet("app.onto"),
  createWallet("llc.besc"),
  createWallet("org.mugambo"),
  createWallet("fi.stablez"),
  createWallet("money.keychain"),
  createWallet("io.trustasset"),
  createWallet("xyz.echooo"),
  createWallet("io.tradestrike"),
  createWallet("gg.indi"),
  createWallet("io.hacken.hai"),
  createWallet("app.xverse"),
  createWallet("com.coinex.wallet"),
  createWallet("io.myabcwallet"),
  createWallet("com.icewal"),
  createWallet("com.bscecowallet"),
  createWallet("finance.voltage"),
  createWallet("com.walletconnect"),
  createWallet("com.reown"),
  createWallet("io.banksocial"),
  createWallet("com.purechain"),
  createWallet("io.ethos"),
  createWallet("com.cryptnox"),
  createWallet("com.it.onewallet"),
  createWallet("network.dgg"),
  createWallet("pub.dg"),
  createWallet("com.reown.appkit-lab"),
  createWallet("app.omni"),
  createWallet("world.qoin"),
  createWallet("com.amazewallet"),
  createWallet("zone.bitverse"),
  createWallet("io.ozonewallet"),
  createWallet("walletConnect"),
  createWallet("embedded"),
  createWallet("inApp"),
  createWallet("smart"),
  createWallet("org.base.account"),
  createWallet("xyz.abs"),
  createWallet("xyz.dawnwallet"),
  createWallet("sh.frame"),
  createWallet("io.useglyph"),
  createWallet("com.lootrush"),
  createWallet("com.blanqlabs.wallet"),
  createWallet("io.runonflux.sspwallet"),
  createWallet("io.hero.wallet"),
  createWallet("network.verified.custody"),
  createWallet("console.utila.io"),
  createWallet("com.micet.wallet"),
  createWallet("world.dolphinode.chain"),
  createWallet("com.blazpay.wallet"),
  createWallet("io.finoa"),
  createWallet("com.scramble"),
  createWallet("com.enkrypt"),
  createWallet("pro.hinkal.walletconnect"),
  createWallet("com.moongate.one"),
  createWallet("tech.levain"),
  createWallet("fund.lflabs"),
  createWallet("io.walletverse"),
  createWallet("com.onlybulls"),
  createWallet("com.mecowallet"),
  createWallet("io.ironwallet"),
  createWallet("app.outlawgames"),
  createWallet("com.rewardywallet"),
  createWallet("io.walletv"),
  createWallet("io.reactwallet"),
  createWallet("today.paywithcrypto.wallet"),
  createWallet("org.lunascape"),
  createWallet("com.nvxowallet"),
  createWallet("com.walllet"),
  createWallet("ai.interlinklabs"),
  createWallet("network.wali"),
  createWallet("at.swe"),
  createWallet("com.tychiwallet"),
  createWallet("com.dlicom"),
  createWallet("com.hashport.wallet"),
  createWallet("com.anchorage"),
  createWallet("io.billionwallet"),
  createWallet("com.tokenb"),
  createWallet("org.onyx"),
  createWallet("io.gk8"),
  createWallet("com.socjsc"),
  createWallet("io.cfcx"),
  createWallet("com.dexari"),
  createWallet("tech.defiantapp"),
];

function Example() {
  return (
    <ConnectButton
      accountAbstraction={{
        chain: ethereum, // replace with the chain you want
        sponsorGas: true,
      }}
      auth={{
        async doLogin(params) {
          // call your backend to verify the signed payload passed in params
        },
        async doLogout() {
          // call your backend to logout the user if needed
        },
        async getLoginPayload(params) {
          // call your backend and return the payload
        },
        async isLoggedIn() {
          // call your backend to check if the user is logged in
        },
      }}
      client={client}
      connectButton={{ label: "Connect" }}
      connectModal={{ size: "compact" }}
      theme={darkTheme({
        colors: { modalBg: "hsl(0, 0%, 4%)" },
      })}
      wallets={wallets}
    />
  );
}
