// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: unused_element

// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class FadakaBindings {
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  FadakaBindings(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  FadakaBindings.fromLookup(ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup)
      : _lookup = lookup;

  /// Fast cryptographic generation executed directly on the main thread isolate.
  int fadaka_generate_keypair(
    ffi.Pointer<ffi.Uint8> out_private_key,
    ffi.Pointer<ffi.Uint8> out_public_key,
  ) {
    return _fadaka_generate_keypair(out_private_key, out_public_key);
  }

  late final _fadaka_generate_keypairPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>>('fadaka_generate_keypair');
  late final _fadaka_generate_keypair =
      _fadaka_generate_keypairPtr.asFunction<int Function(ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>)>();

  /// Formulates signature metadata natively.
  int fadaka_sign_transaction(
    ffi.Pointer<ffi.Uint8> private_key,
    ffi.Pointer<ffi.Uint8> tx_payload,
    int payload_len,
    ffi.Pointer<ffi.Uint8> out_signature,
  ) {
    return _fadaka_sign_transaction(private_key, tx_payload, payload_len, out_signature);
  }

  late final _fadaka_sign_transactionPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>, ffi.Int32,
              ffi.Pointer<ffi.Uint8>)>>('fadaka_sign_transaction');
  late final _fadaka_sign_transaction = _fadaka_sign_transactionPtr.asFunction<
      int Function(ffi.Pointer<ffi.Uint8>, ffi.Pointer<ffi.Uint8>, int, ffi.Pointer<ffi.Uint8>)>();

  /// CRITICAL: Long-running native event loops should be executed on a separate worker Isolate
  /// to prevent dropping UI presentation frames in Flutter applications.
  int fadaka_initialize_node_loop(
    ffi.Pointer<ffi.Char> node_config_json,
  ) {
    return _fadaka_initialize_node_loop(node_config_json);
  }

  late final _fadaka_initialize_node_loopPtr =
      _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Char>)>>('fadaka_initialize_node_loop');
  late final _fadaka_initialize_node_loop =
      _fadaka_initialize_node_loopPtr.asFunction<int Function(ffi.Pointer<ffi.Char>)>();
}
